<?php
// setup.php - Automatic Database and Connection Configurator for KS Electrical and AC Services

$host = '127.0.0.1'; // Fast localhost connection on Windows
$sql_file = __DIR__ . '/database/store.sql';

// Common local development credentials to try
$credentials = [
    ['username' => 'root', 'password' => ''],      // Default for XAMPP
    ['username' => 'root', 'password' => 'root']    // Default for MAMP / custom setups
];

$connected = false;
$conn = null;
$chosen_user = '';
$chosen_pass = '';

foreach ($credentials as $cred) {
    try {
        $conn = @new mysqli($host, $cred['username'], $cred['password']);
        if (!$conn->connect_error) {
            $connected = true;
            $chosen_user = $cred['username'];
            $chosen_pass = $cred['password'];
            break;
        }
    } catch (Exception $e) {
        // try next
    }
}

if (!$connected) {
    echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #dc3545; border-radius: 5px; background-color: #f8d7da; color: #721c24;'>";
    echo "<h2>Database Connection Error</h2>";
    echo "<p>Could not connect to the MySQL server on <b>127.0.0.1 / localhost</b>.</p>";
    echo "<p><b>Please ensure that:</b></p>";
    echo "<ul>";
    echo "<li>Your MySQL server (like XAMPP, WampServer, or standalone MySQL) is running.</li>";
    echo "<li>The MySQL server is listening on port 3306.</li>";
    echo "</ul>";
    echo "<p>We tried connecting with default credentials (username 'root' with empty password, and username 'root' with password 'root').</p>";
    echo "</div>";
    exit;
}

// Create database if not exists
$dbname = 'store';
$create_db_query = "CREATE DATABASE IF NOT EXISTS `$dbname` CHARACTER SET utf8 COLLATE utf8_general_ci";
if (!$conn->query($create_db_query)) {
    echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #dc3545; border-radius: 5px; background-color: #f8d7da; color: #721c24;'>";
    echo "<h2>Error Creating Database</h2>";
    echo "<p>Failed to create database '$dbname': " . $conn->error . "</p>";
    echo "</div>";
    exit;
}

// Select database
if (!$conn->select_db($dbname)) {
    echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #dc3545; border-radius: 5px; background-color: #f8d7da; color: #721c24;'>";
    echo "<h2>Error Selecting Database</h2>";
    echo "<p>Could not select database '$dbname': " . $conn->error . "</p>";
    echo "</div>";
    exit;
}

// Import SQL dump
if (!file_exists($sql_file)) {
    echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #dc3545; border-radius: 5px; background-color: #f8d7da; color: #721c24;'>";
    echo "<h2>SQL File Not Found</h2>";
    echo "<p>Could not locate the schema file at <code>$sql_file</code>.</p>";
    echo "</div>";
    exit;
}

$sql_content = file_get_contents($sql_file);

// Parse SQL queries
$queries = [];
$lines = explode("\n", $sql_content);
$temp_query = '';

foreach ($lines as $line) {
    $line = trim($line);
    if ($line === '' || strpos($line, '--') === 0 || strpos($line, '#') === 0 || strpos($line, '/*') === 0) {
        continue;
    }
    
    $temp_query .= $line . "\n";
    if (substr($line, -1) === ';') {
        $queries[] = $temp_query;
        $temp_query = '';
    }
}

$success_count = 0;
$error_count = 0;

foreach ($queries as $query) {
    if (trim($query) !== '') {
        if ($conn->query($query)) {
            $success_count++;
        } else {
            $error_count++;
        }
    }
}

// Update php_action/db_connect.php dynamically
$db_connect_path = __DIR__ . '/php_action/db_connect.php';

$dynamic_url_code = '
$protocol = (!empty($_SERVER[\'HTTPS\']) && $_SERVER[\'HTTPS\'] !== \'off\' || $_SERVER[\'SERVER_PORT\'] == 443) ? "https://" : "http://";
$host = $_SERVER[\'HTTP_HOST\'];
$base_dir = str_replace(\'\\\\\', \'/\', dirname($_SERVER[\'SCRIPT_NAME\']));
$base_dir = preg_replace(\'/(\\\/php_action|\\\/custom|\\\/includes)$/\', \'\', rtrim($base_dir, \'/\'));
$store_url = $protocol . $host . ($base_dir === \'\' ? \'/\' : $base_dir . \'/\');
';

$new_db_connect_content = "<?php 	
// Auto-generated by setup.php on setup

\$localhost = \"$host\";
\$username = \"$chosen_user\";
\$password = \"$chosen_pass\";
\$dbname = \"$dbname\";

$dynamic_url_code

// db connection
\$connect = new mysqli(\$localhost, \$username, \$password, \$dbname);

// check connection
if(\$connect->connect_error) {
  die(\"Connection Failed : \" . \$connect->connect_error);
}
?>";

if (file_put_contents($db_connect_path, $new_db_connect_content) === false) {
    echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #ffc107; border-radius: 5px; background-color: #fff3cd; color: #856404;'>";
    echo "<h2>Partial Setup Success</h2>";
    echo "<p>Database <b>$dbname</b> was setup successfully, but we could not write settings to <code>php_action/db_connect.php</code>.</p>";
    echo "<p>Please copy the code below and save it inside <code>php_action/db_connect.php</code> manually:</p>";
    echo "<pre style='background: #f1f1f1; padding: 10px; overflow-x: auto;'>" . htmlspecialchars($new_db_connect_content) . "</pre>";
    echo "</div>";
    exit;
}

echo "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 30px; border: 1px solid #28a745; border-radius: 5px; background-color: #d4edda; color: #155724; text-align: center;'>";
echo "<h1>Setup Successful!</h1>";
echo "<p>Database <b>$dbname</b> has been created and initialized.</p>";
echo "<p>Imported <b>$success_count</b> queries from <code>database/store.sql</code>.</p>";
echo "<p>Configuration file <code>php_action/db_connect.php</code> updated successfully with auto-detected settings.</p>";
echo "<br><br>";
echo "<a href='index.php' style='display: inline-block; padding: 12px 24px; background-color: #28a745; color: white; text-decoration: none; border-radius: 5px; font-weight: bold;'>Go to Login Page</a>";
echo "</div>";
?>
